[build]
  publish = "."

[functions]
  node_bundler = "esbuild"

[context.production.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
